stages:
  - check
  - test-all
  - publish

variables:
    REGISTRY_PROJECT_ID: "21689940"

check:
  stage: check
  image: python:3.9
  script:
    - pip install flake8
    - flake8
    - pip install pytest pytest-cov mypy
    - mypy --strict applipy_inject/ tests/
    - pytest --cov=applipy_inject --cov-report=term-missing

# tests-X.Y:
#   stage: test-all
#   image: python:X.Y
#   script:
#     - pip install pytest mypy
#     - mypy --strict applipy_inject/ tests/
#     - pytest

publish-gitlab:
  stage: publish
  image: python:latest
  variables:
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: "${CI_JOB_TOKEN}"
    TWINE_REPOSITORY_URL: "https://gitlab.com/api/v4/projects/${REGISTRY_PROJECT_ID}/packages/pypi"
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  only:
    refs:
      - master
    changes:
      - applipy_inject/version.py

publish-pypi:
  stage: publish
  image: python:latest
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: "${PYPI_TOKEN}"
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  only:
    refs:
      - master
    changes:
      - applipy_inject/version.py
